### ISSUE TITLE
Python 3 & cryptography support

### ISSUE THREAD

**Issue by RazerM** [georgebrock/1pass#26]
[I forked 1pass](https://github.com/RazerM/1pass) to a) add Python 3 support and b) use [cryptography](http://cryptography.io) instead of M2Crypto (I had trouble installing).

I started doing this without intending to re-upload to GitHub, but perhaps you might want to merge some or all of these changes in.

All the tests should pass on Python 2 and 3, unless I broke something while cleaning up the git history.

**Comment by AdamIsrael** [comment]
Hi Razer,

Sorry for missing this! I just merged in my PR that does similar to add Python 3 support.
