### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by georgebrock** [georgebrock/1pass#32]
I started this project to scratch my own itch. However, I've now stopped using 1password as my personal password store, and so maintaining this project is no longer easy (because I don't have a regularly updated 1password vault to try things out with) or interesting (because I don't use this anymore—it's not even installed on my latest laptop).

I'm using [pass(1)][1] instead these days. The portability and basis on open technology really appeal to me (PGP for encryption; Git for change management and syncing; shell for the interface).

[1]: https://www.passwordstore.org/

**Comment by AdamIsrael** [comment]
Hey,

I'd be willing to maintain this. I'm writing an app indicator to interface with 1password, using this library, and was just starting to look at updating/extending functionality.

**Comment by georgebrock** [comment]
@AdamIsrael Great, thanks! I've given you commit access to the repo. Let's do a release or two like this, and then I'll completely transfer the repo to your account. Does that sound workable?

**Comment by AdamIsrael** [comment]
Yep, that works for me I'm doing a refactor to use pycrypto instead of m2crypto at the moment (m2crypto fails with undefined symbols on Ubuntu 16.04), so I'll open a pull request for that sometime this week.

**Comment by devth** [comment]
ref https://github.com/georgebrock/1pass/pull/34

**Comment by AlJohri** [comment]
Thanks for stepping up @AdamIsrael! Really looking forward to using this on Python 3.

**Comment by AdamIsrael** [comment]
I think it's safe to close this issue now. :) #34 is now merged, which introduces python3 compatibility.
