### ISSUE TITLE
ImportError: No module named 'keychain'

### ISSUE THREAD

**Issue by RomainPiel** [georgebrock/1pass#33]
Hi,
(sorry I'm new to python)
After checking out the source and running the binary in my terminal, I got:
```
Traceback (most recent call last):
  File "bin/1pass", line 7, in <module>
    import onepassword.cli
  File "bin/../onepassword/__init__.py", line 1, in <module>
    from keychain import Keychain
ImportError: No module named 'keychain'
```

Any idea what could cause that?

Thanks!

**Comment by alexmuller** [comment]
What version of Python are you running? I suspect this is a problem caused by running with Python 3.

**Comment by AdamIsrael** [comment]
Hi Romain,

The latest version on github has Python3 support so this should no longer be an issue. Please feel free to re-open the issue if you're still running into the issue.
